---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
    kustomize.toolkit.fluxcd.io/prune: Disabled
type: Opaque
stringData:
  # be sure you are generating an API token and not a global API key
  # https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
  cloudflare-token: 123abc
