---
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: default-whitelist
  namespace: default
spec:
  ipAllowList:
    sourceRange:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
      - "172.16.0.0/12"
