---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-valkey-secret
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
    kustomize.toolkit.fluxcd.io/prune: Disabled
type: Opaque
stringData:
  valkey-password: password
