---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: database
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
    kustomize.toolkit.fluxcd.io/prune: Disabled
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: user@domain.com
  PGADMIN_DEFAULT_PASSWORD: password
