---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Secret
metadata:
  name:  s3-bucket-cloudnative-pg-secret
  namespace: database
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Ignore
    kustomize.toolkit.fluxcd.io/prune: Disabled
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <your-aws-access-key-id>
  AWS_SECRET_ACCESS_KEY: <your-aws-secret-access-key>
