# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: default
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2024.8.1
      sourceRef:
        # renovate: datasource=helm depName=authentik repository=https://charts.goauthentik.io
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  install:
    createNamespace: true
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    - name: authentik-valkey
      namespace: default
    - name: traefik
      namespace: traefik
  valuesFrom:
    - kind: Secret
      name: authentik-values-secret
      valuesKey: authentik-secret_key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-values-secret
      valuesKey: authentik-email-username
      targetPath: authentik-email-username
    - kind: Secret
      name: authentik-values-secret
      valuesKey: authentik-email-password
      targetPath: authentik.email.password
    - kind: Secret
      name: authentik-values-secret
      valuesKey: authentik-email-from
      targetPath: authentik.email.from
    - kind: Secret
      name: authentik-values-secret
      valuesKey: authentik-postgresql-password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-valkey-secret
      valuesKey: valkey-password
      targetPath: authentik.redis.password
  values:
    global:
      env:
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__1__HOST
          value: "postgres-ro.database.svc.cluster.local"
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__1__NAME
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__1__USER
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__1__PORT
          value: "5432"
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__1__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-values-secret
              key: authentik-postgresql-password
    authentik:
      email:
        host: smtp.mailgun.org
        port: 587
        use_tls: true
        use_ssl: false
        timeout: 10
      postgresql:
        host: postgres-rw.database.svc.cluster.local
        name: authentik
        port: 5432
      redis:
        host: authentik-valkey-master.default.svc.cluster.local
    blueprints:
      # -- List of config maps to mount blueprints from.
      # Only keys in the configMap ending with `.yaml` will be discovered and applied.
      configMaps:
        - authentik-blueprints-configmap
      # -- List of secrets to mount blueprints from.
      # Only keys in the secret ending with `.yaml` will be discovered and applied.
#      secrets: []
    server:
      replicas: 1
    worker:
      replicas: 1
