---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./HelmRelease.yaml
  - ./IngressRoute.yaml
configMapGenerator:
  - name: authentik-blueprints-configmap
    files:
      - default-source-authentication.yaml=./resources/default-source-authentication.yaml
      - password-and-mfa-loose-authentication.yaml=./resources/password-and-mfa-loose-authentication.yaml
      - password-and-mfa-strict-authentication.yaml=./resources/password-and-mfa-strict-authentication.yaml
      - password-authentication.yaml=./resources/password-authentication.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
