# Title: Pi-hole
# Description: Pi-hole DNS and DHCP Server

version: '3'

services:
  pihole:
    image: pihole/pihole:2024.02.2
    container_name: pihole
    restart: always
    cap_add:
        - NET_ADMIN
    network_mode: "host"
    # ports:
    #   - "53:53/tcp" # DNS
    #   - "53:53/udp" # DNS
    #   - "67:67/udp" # DHCP
    #   - "${PORT}:${PORT}/tcp" # WebUI
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      WEB_PORT: ${PORT}
    volumes:
      - "${DIR_ETC_PIHOLE}:/etc/pihole"
      - "${DIR_ETC_DNSMASQ_D}:/etc/dnsmasq.d"
    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: pihole-rewrite
      - "traefik.http.routers.pihole-rewrite.entrypoints=https"
      - "traefik.http.routers.pihole-rewrite.rule=Host(`${DOMAIN}`) && !PathPrefix(`/admin`)"
      - "traefik.http.routers.pihole-rewrite.middlewares=addprefix-pihole,secured@file"
      - "traefik.http.routers.pihole-rewrite.tls=true"
      - "traefik.http.routers.pihole-rewrite.tls.certresolver=${CERT_RESOLVER}" # staging or production
      - "traefik.http.routers.pihole-rewrite.service=pihole@file"
      # router: pihole-redirect
      - "traefik.http.routers.pihole-redirect.entrypoints=https"
      - "traefik.http.routers.pihole-redirect.rule=Host(`${DOMAIN}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.pihole-redirect.middlewares=redirectregex-pihole,secured@file"
      - "traefik.http.routers.pihole-redirect.tls=true"
      - "traefik.http.routers.pihole-redirect.tls.certresolver=${CERT_RESOLVER}" # staging or production
      - "traefik.http.routers.pihole-redirect.service=pihole@file"
      - "traefik.http.routers.pihole-redirect.priority=1000"
      # service: pihole
      - "traefik.http.services.pihole.loadbalancer.server.port=${PORT}"
      # middleware: addprefix-pihole
      - "traefik.http.middlewares.addprefix-pihole.addprefix.prefix=/admin"
      # middleware: redirectregex-pihole
      - "traefik.http.middlewares.redirectregex-pihole.redirectregex.regex=^https://${DOMAIN}/admin(.*)"
      - "traefik.http.middlewares.redirectregex-pihole.redirectregex.replacement=https://${DOMAIN}$${1}"
      # Homepage Dashboard
      - homepage.group=Networking
      - homepage.name=PiHole
      - homepage.icon=pi-hole
      - homepage.href=https://${DOMAIN}
      - homepage.description=DNS, Network Ad-Blocker
      - homepage.weight=20
      - homepage.widget.type=pihole
      - homepage.widget.fields=["queries", "blocked", "blocked_percent", "gravity"]
      - homepage.widget.url=https://${DOMAIN}
      - homepage.widget.version=5
      - homepage.widget.key=${HOMEPAGE_VAR_PIHOLE_KEY}
