# Title: Pi-hole
# Description: Pi-hole DNS and DHCP Server

version: '3'

services:
  pihole:
    image: pihole/pihole:2025.03.0
    container_name: pihole
    restart: always
    cap_add:
        - NET_ADMIN
    network_mode: "host"
    # ports:
    #   - "53:53/tcp" # DNS
    #   - "53:53/udp" # DNS
    #   - "67:67/udp" # DHCP
    #   - "${PORT}:${PORT}/tcp" # WebUI
    environment:
      TZ: ${TZ:-Europe/Berlin}
      WEBPASSWORD: ${WEBPASSWORD}
      WEB_PORT: ${PORT:-80}
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
    volumes:
      - ${DIR_DATA}/pihole-data/data:/etc/pihole
      - ${DIR_DATA}/pihole-data/dnsmasq.d:/etc/dnsmasq.d

    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: pihole-rewrite
      - "traefik.http.routers.pihole-rewrite.entrypoints=https"
      - "traefik.http.routers.pihole-rewrite.rule=Host(`${DOMAIN_PIHOLE:-pihole.pixelstack.live}`) && !PathPrefix(`/admin`)"
      - "traefik.http.routers.pihole-rewrite.middlewares=addprefix-pihole,secured@file"
      - "traefik.http.routers.pihole-rewrite.tls=true"
      - "traefik.http.routers.pihole-rewrite.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      - "traefik.http.routers.pihole-rewrite.service=pihole@file"
      # router: pihole-redirect
      - "traefik.http.routers.pihole-redirect.entrypoints=https"
      - "traefik.http.routers.pihole-redirect.rule=Host(`${DOMAIN_PIHOLE:-pihole.pixelstack.live}}`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.pihole-redirect.middlewares=redirectregex-pihole,secured@file"
      - "traefik.http.routers.pihole-redirect.tls=true"
      - "traefik.http.routers.pihole-redirect.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      - "traefik.http.routers.pihole-redirect.service=pihole@file"
      - "traefik.http.routers.pihole-redirect.priority=1000"
      # service: pihole
      - "traefik.http.services.pihole.loadbalancer.server.port=${PORT:-80}"
      # middleware: addprefix-pihole
      - "traefik.http.middlewares.addprefix-pihole.addprefix.prefix=/admin"
      # middleware: redirectregex-pihole
      - "traefik.http.middlewares.redirectregex-pihole.redirectregex.regex=^https://${DOMAIN_PIHOLE:-pihole.pixelstack.live}/admin(.*)"
      - "traefik.http.middlewares.redirectregex-pihole.redirectregex.replacement=https://${DOMAIN_PIHOLE:-pihole.pixelstack.live}$${1}"
      # Homepage Dashboard
      - homepage.group=Networking
      - homepage.name=PiHole
      - homepage.icon=pi-hole
      - homepage.href=https://${DOMAIN_PIHOLE:-pihole.pixelstack.live}}
      - homepage.description=DNS, Network Ad-Blocker
      - homepage.weight=20
      - homepage.widget.type=pihole
      - homepage.widget.fields=["queries", "blocked", "blocked_percent", "gravity"]
      - homepage.widget.url=https://${DOMAIN_PIHOLE:-pihole.pixelstack.live}
      - homepage.widget.version=5
      - homepage.widget.key=${HOMEPAGE_VAR_PIHOLE_KEY}
