# Title: omada-controller
# Description: TP-Link Omada Controller

version: "3"

services:
  omada-controller:
    image: mbentley/omada-controller:5.12
    container_name: omada-controller
    restart: unless-stopped
    network_mode: host
    ports:
      - "8088:8088"
      # - "8043:8043"
      # - "8843:8843"
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
      - "29814:29814"
      - "29815:29815"
      - "29816:29816"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    environment:
      MANAGE_HTTP_PORT: 8088
      # MANAGE_HTTPS_PORT: 8043
      PORTAL_HTTP_PORT: 8088
      # PORTAL_HTTPS_PORT: 8843
      PORT_ADOPT_V1: 29812
      PORT_APP_DISCOVERY: 27001
      PORT_DISCOVERY: 29810
      PORT_MANAGER_V1: 29811
      PORT_MANAGER_V2: 29814
      PORT_UPGRADE_V1: 29813
      PUID: ${PUID}
      PGID: ${PGID}
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      # Name of the public cert chain mounted to /cert
      # SSL_CERT_NAME: "tls.crt"
      # Name of the private key mounted to /cert
      # SSL_KEY_NAME: "tls.key"
      TZ: ${TZ}
    volumes:
     - "${dir_data}:/opt/tplink/EAPController/data"
     - "${dir_logs}:/opt/tplink/EAPController/logs"