# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cert-manager
  namespace: cert-manager
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      # renovate: datasource=helm depName=cert-manager repository=https://charts.jetstack.io
      chart: cert-manager
      version: v1.15.3
      sourceRef:
        kind: HelmRepository
        name: cert-manager-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
    replicaCount: 1
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 9.9.9.9
