# Title: Filebrowser
# Description: Web-based file manager

version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    container_name: filebrowser
    restart: always
    user: ${PUID}:${PGID}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80"]
      interval: 10s
      timeout: 10s
      start_period: 20s
      retries: 3
    networks:
      - proxy
    ports:
      - 8082:80
    volumes:
      - ${DIR_SRV}:/srv
      - ${FILE_DB}:/database.db
      - ${FILE_CONFIG}:/.filebrowser.json
    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: filebrowser
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.filebrowser.middlewares=secured@file"
      - "traefik.http.routers.filebrowser.service=filebrowser"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=${CERT_RESOLVER}" # staging or production
      # service: filebrowser
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      # Homepage Dashboard
      - homepage.group=Management
      - homepage.name=Filebrowser
      - homepage.icon=filebrowser
      - homepage.href=https://${DOMAIN}
      - homepage.description=Web-based file manager
      - homepage.weight=40

networks:
  proxy:
    external: true
