FROM fyb3roptik/threadfin:1.0.24

# Packages for Streamkink
RUN apt-get install -y python3 \
                       libxml2-dev \
                       libxslt-dev \
                       python3-pip \
                       streamlink
