# Title: threadfin-stack
# Description: M3U Proxy for live TV and converter for HLS streams to MPEG-TS

version: "3"

services:
  threadfin:
    image: fyb3roptik/threadfin:1.2.9
    container_name: threadfin
    restart: always
    networks:
      - proxy
    ports:
      - ${PORT_THREADFIN}:${PORT_THREADFIN}
    environment:
      TZ: ${TZ}
      THREADFIN_PORT: ${PORT_THREADFIN}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DIR_THREADFIN_CONF}:/home/threadfin/conf
    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: threadfin
      - "traefik.http.routers.threadfin.entrypoints=https"
      - "traefik.http.routers.threadfin.rule=Host(`${DOMAIN_THREADFIN}`)"
      - "traefik.http.routers.threadfin.middlewares=secured@file"
      - "traefik.http.routers.threadfin.service=threadfin"
      - "traefik.http.routers.threadfin.tls=true"
      - "traefik.http.routers.threadfin.tls.certresolver=${CERT_RESOLVER}" # staging or production
      # service: threadfin
      - "traefik.http.services.threadfin.loadbalancer.server.port=${PORT_THREADFIN}"
      # Homepage Dashboard
      - homepage.group=Providers
      - homepage.name=Threadfin
      - homepage.icon=mdi-antenna
      - homepage.href=https://${DOMAIN_THREADFIN}
      - homepage.description=M3U Proxy for live TV
      - homepage.weight=20

  tf-streamlink:
    image: tf-streamlink:1.0.24
    container_name: tf-streamlink
    restart: always
    networks:
      - proxy
    ports:
      - ${PORT_TF_STREAMLINK}:${PORT_TF_STREAMLINK}
    environment:
      TZ: ${TZ}
      THREADFIN_PORT: ${PORT_TF_STREAMLINK}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DIR_TF_STREAMLINK_CONF}:/home/threadfin/conf
    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: tf-streamlink
      - "traefik.http.routers.tf-streamlink.entrypoints=https"
      - "traefik.http.routers.tf-streamlink.rule=Host(`${DOMAIN_TF_STREAMLINK}`)"
      - "traefik.http.routers.tf-streamlink.middlewares=secured@file"
      - "traefik.http.routers.tf-streamlink.service=tf-streamlink"
      - "traefik.http.routers.tf-streamlink.tls=true"
      - "traefik.http.routers.tf-streamlink.tls.certresolver=${CERT_RESOLVER}" # staging or production
      # service: tf-streamlink
      - "traefik.http.services.tf-streamlink.loadbalancer.server.port=${PORT_TF_STREAMLINK}"
      # Homepage Dashboard
      - homepage.group=Providers
      - homepage.name=Threadfin Streamlink
      - homepage.icon=mdi-antenna
      - homepage.href=https://${DOMAIN_TF_STREAMLINK}
      - homepage.description=Converter for HLS streams to MPEG-TS
      - homepage.weight=30

networks:
  proxy:
    external: true
