---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rancher-charts
  namespace: flux-system
spec:
  interval: 5m
  url: https://releases.rancher.com/server-charts/stable
