# Title: WireGuard Portal
# Description: Web interface for managing WireGuard VPN
#
# CONFIGURATION NOTES:
# - Server PostUp: iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# - Server PostDown: iptables -D FORWARD -i wg0 -j ACCEPT 2>/dev/null || true; iptables -D FORWARD -o wg0 -j ACCEPT 2>/dev/null || true; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE 2>/dev/null || true
# - Client DNS: Set to your DNS server
# - Client AllowedIPs: Set to 0.0.0.0/0, ::/0 for full VPN routing

services:
  wireguard-portal:
    image: wgportal/wg-portal:v2.0.2
    container_name: wireguard-portal
    restart: always
    networks:
      - proxy
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      # - "8888:8888"
      - "51820:51820/udp" 
    environment:
      WG_PORTAL_ADMIN_USER: ${WG_PORTAL_ADMIN_USER}
      WG_PORTAL_ADMIN_PASS: ${WG_PORTAL_ADMIN_PASS}
      WG_PORTAL_DB_ENCRYPTION_PASSPHRASE: ${WG_PORTAL_DB_ENCRYPTION_PASSPHRASE}
      WG_PORTAL_EMAIL_HOST: ${WG_PORTAL_EMAIL_HOST}
      WG_PORTAL_EMAIL_PORT: ${WG_PORTAL_EMAIL_PORT}
      WG_PORTAL_EMAIL_ENCRYPTION: ${WG_PORTAL_EMAIL_ENCRYPTION}
      WG_PORTAL_EMAIL_USERNAME: ${WG_PORTAL_EMAIL_USERNAME}
      WG_PORTAL_EMAIL_PASSWORD: ${WG_PORTAL_EMAIL_PASSWORD}
      WG_PORTAL_EMAIL_AUTH_TYPE: ${WG_PORTAL_EMAIL_AUTH_TYPE}
      WG_PORTAL_EMAIL_FROM: ${WG_PORTAL_EMAIL_FROM}
      AUTHENTIK_LOGOUT_REDIRECT_URL: ${AUTHENTIK_LOGOUT_REDIRECT_URL}
      AUTHENTIK_CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
      AUTHENTIK_CLIENT_SECRET: ${AUTHENTIK_CLIENT_SECRET}
      AUTHENTIK_SERVER_URL: ${AUTHENTIK_SERVER_URL}
      WG_PORTAL_SESSION_SECRET: ${WG_PORTAL_SESSION_SECRET}
      WG_PORTAL_CSRF_SECRET: ${WG_PORTAL_CSRF_SECRET}
    volumes:
      - ${DIR_DATA}/data:/app/data
      - ${DIR_DATA}/config:/app/config
    labels:
      # Traefik 3.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: wg-portal
      - "traefik.http.routers.wg-portal.entrypoints=https"
      - "traefik.http.routers.wg-portal.rule=Host(`${DOMAIN_WG_PORTAL:-wg-portal.pixelstack.live}`)"
      - "traefik.http.routers.wg-portal.middlewares=secured@file"
      - "traefik.http.routers.wg-portal.service=wg-portal"
      - "traefik.http.routers.wg-portal.tls=true"
      - "traefik.http.routers.wg-portal.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      # service: wg-portal
      - "traefik.http.services.wg-portal.loadbalancer.server.port=8888"
      # Homepage Dashboard
      - homepage.group=Networking
      - homepage.name=Wireguard Portal
      - homepage.icon=wireguard
      - homepage.href=https://${DOMAIN_WG_PORTAL:-wg-portal.pixelstack.live}
      - homepage.description=Web UI for WireGuard VPN
      - homepage.weight=30

networks:
  proxy:
    external: true
