---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    cnpg.io/cluster: postgres
    role: primary
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
