---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik-valkey
  namespace: default
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      chart: valkey
      reconcileStrategy: ChartVersion
      version: 0.3.15
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install:
    createNamespace: true
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    global:
      defaultStorageClass: longhorn
    architecture: standalone
    auth:
      existingSecret: authentik-valkey-secret
      existingSecretPasswordKey: valkey-password
    master:
      persistence:
        size: 2Gi
    replica:
      persistence:
        size: 2Gi
