# Title: Database
# Description: PostgreSQL and Redis for various services
# Note: For pgAdmin to work with presistent data, the volume must have
#       r/w permissions for the UID 5050

version: '3'

services:
  postgresql:
    image: docker.io/library/postgres:12.18-alpine3.19
    container_name: postgresql
    restart: always
    networks:
      - proxy
    # ports:
    #   - 5432:5432  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
    volumes:
      - ${DIR_DB_DATA}:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: postresql
      - "traefik.tcp.routers.postgresql.entrypoints=postgres"
      - "traefik.tcp.routers.postgresql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgresql.middlewares=default-whitelist@file"
      - "traefik.tcp.routers.postgresql.service=postgresql"
      # service: postgresql
      - "traefik.tcp.services.postgresql.loadbalancer.server.port=5432"

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80/misc/ping"]
      start_period: 160s
      interval: 10s
      retries: 3
      timeout: 10s
    networks:
      - proxy
    # ports:
    #   - 8085:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL_PGA}
      PGADMIN_DEFAULT_PASSWORD: ${PASS_PGA}
    volumes:
      - ${DIR_PGADMIN}:/var/lib/pgadmin
      - ${FILE_PGADMIN_CONF}:/pgadmin4/config_local.py:ro
    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: pgadmin
      - "traefik.http.routers.pgadmin.entrypoints=https"
      - "traefik.http.routers.pgadmin.rule=Host(`${DOMAIN_PGA}`)"
      - "traefik.http.routers.pgadmin.middlewares=secured@file"
      - "traefik.http.routers.pgadmin.service=service=pgadmin@file"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=${CERT_RESOLVER}" # staging or production
      # service: pgadmin
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      # Homepage Dashboard
      - homepage.group=Providers
      - homepage.name=PgAdmin
      - homepage.icon=pgadmin
      - homepage.href=https://${DOMAIN_PGA}
      - homepage.description=Database Management
      - homepage.weight=10

networks:
  proxy:
    external: true
