# Title: Tvheadend
# Description: Tvheadend is a TV streaming server and recorder for Linux.

version: '3'

services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    restart: always
    network_mode: host
    ports:
      - 9981:9981
      - 9982:9982
    environment:
      PUID: ${PUID:1000}
      PGID: ${PGID:1000}
      TZ: ${TZ:-Europe/Berlin}
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: python3|python3-pip|python3-venv|libxml2-dev|libxslt-dev
      INSTALL_PIP_PACKAGES: setuptools|wheel|versioningit|certifi|isodate|pycountry|pycryptodome|pysocks|requests|trio|trio-websocket|typing_extensions|urllib3|websocket-client|streamlink
#      RUN_OPTS: --noacl
    volumes:
      - ${DIR_DATA}/tvheadend-data/config:/config
