# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rancher
  namespace: cattle-system
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      # renovate: datasource=helm depName=rancher repository=https://releases.rancher.com/server-charts/stable
      chart: rancher
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    domain: rancher.pixelstack.live
    bootstrapPassword: admin
    replicas: 2
    ingress:
      enabled: false
    tls: external
    ingressClassName: traefik
