# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudnativepg
  namespace:  database
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.22.0
      sourceRef:
        # renovate: datasource=helm depName=cluster repository=https://cloudnative-pg.github.io/charts
        kind: HelmRepository
        name: cloudnativepg-charts
        namespace: flux-system
  install:
    createNamespace: true
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    crds:
      create: true
