# Title: jellyfin
# Description: Media server

version: "3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.13
    container_name: jellyfin
    restart: unless-stopped
    # by id as these may not exist within the container. 
    # Needed to provide permissions to the VAAPI Devices
    group_add: 
      - '107' # render
      - '44' # video
    network_mode: 'host' # Needed for DLNA
    ports:
      - 8096:8096 # Http webUI
      - 8920:8920 # Https webUI (certificate required)
      - 7359:7359/udp # Jellyfin local network discovery
      - 1900:1900/udp # DNLA/service discovery
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
      - "/dev/video13:/dev/video13"
      - "/dev/video14:/dev/video14"
      - "/dev/video15:/dev/video15"
      - "/dev/video16:/dev/video16"
      - "/dev/video18:/dev/video18"
      - "/dev/video19:/dev/video19"
      - "/dev/video20:/dev/video20"
      - "/dev/video21:/dev/video21"
      - "/dev/video22:/dev/video22"
      - "/dev/video23:/dev/video23"
      - "/dev/video31:/dev/video31"
      - "/dev/media1:/dev/media1"
      - "/dev/media2:/dev/media2"
      - "/dev/media3:/dev/media3"
    volumes:
      - "${DIR_CONFIG}:/config"
      - "${DIR_CACHE}:/cache"
      - "${DIR_MEDIA}:/media"
    labels:
      - "traefik.enable=true"
      # router: jellyfin
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-headers,default-whitelist@file"
      - "traefik.http.routers.jellyfin.service=jellyfin@file"
      - "traefik.http.routers.jellyfin.tls=true"
      # service: jellyfin
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096" 
      - "traefik.http.services.jellyfin.loadbalancer.passHostHeader=true"
      # middleware: jellyfin-headers
      - "traefik.http.middlewares.jellyfin-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.jellyfin-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.SSLForceHost=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.jellyfin-headers.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.middlewares.jellyfin-headers.headers.customresponseheaders.X-XSS-PROTECTION=0"
