# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
spec:
  releaseName: *app
  interval: 5m
  chart:
    spec:
      # renovate: datasource=helm depName=longhorn repository=https://charts.longhorn.io
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    defaultSettings:
      backupTarget: s3://lotr@eu-west/longhorn/
      backupTargetCredentialSecret: s3-bucket-secret
      allowRecurringJobWhileVolumeDetached: true
