# Title: Portainer
# Description: A lightweight Docker management UI.

version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DIR_DATA}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: portainer-frontend
      - "traefik.http.routers.portainer-frontend.entrypoints=https"
      - "traefik.http.routers.portainer-frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.portainer-frontend.middlewares=secured@file"
      - "traefik.http.routers.portainer-frontend.service=portainer-frontend"
      - "traefik.http.routers.portainer-frontend.tls=true"
      # router: portainer-edge
      # - "traefik.http.routers.portainer-edge.entrypoints=https"
      # - "traefik.http.routers.portainer-edge.rule=Host(`${DOMAIN}`)"
      # - "traefik.http.routers.portainer-edge.service=portainer-edge"
      # - "traefik.http.routers.portainer-edge.tls=true"
      # service: portainer
      - "traefik.http.services.portainer-frontend.loadbalancer.server.port=9000"
      # - "traefik.http.services.portainer-edge.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true