# Title: WireGuard Portal
# Description: Web interface for managing WireGuard VPN

version: "3"

services:
  wireguard-portal:
    image: wgportal/wg-portal:v2.0.0-alpha.2
    container_name: wireguard-portal
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8888:8888"
    environment:
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      CONFIG_FILE: /app/config/config.yml
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ${DIR_UI_DATA}:/app/data
      - /etc/wireguard:/etc/wireguard
      - ${FILE_UI_CONFIG}:/app/config/config.yml
    labels:
      # Traefik 2.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: wg-portal
      - "traefik.http.routers.wg-portal.entrypoints=https"
      - "traefik.http.routers.wg-portal.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wg-portal.middlewares=secured@file"
      - "traefik.http.routers.wg-portal.service=wg-portal@file"
      - "traefik.http.routers.wg-portal.tls=true"
      - "traefik.http.routers.wg-portal.tls.certresolver=${CERT_RESOLVER}" # staging or production
      # service: wg-portal
      - "traefik.http.services.wg-portal.loadbalancer.server.port=8888"
      # Homepage Dashboard
      - homepage.group=Networking
      - homepage.name=Wireguard Portal
      - homepage.icon=wireguard
      - homepage.href=https://${DOMAIN}
      - homepage.description=Web UI for WireGuard VPN
      - homepage.weight=30

networks:
  proxy:
    external: true
