core:
  create_default_peer: false
  create_default_peer_on_creation: false

mail:
  host: smtp.example.com
  port: 587
  encryption: starttls
  username: username
  password: password
  auth_type: login
  from: Wireguard Portal noreply@wireguard.local

database:
  type: postgres
  dsn: postgresql://wireguard-portal:password@postgres.example.com:5432/wireguard-portal
  
web:
  external_url: https://wg-portal.example.com
  listening_address: :8888

auth:
  callback_url_prefix: https://wg-portal.example.com/api/v0
  oidc:
    - id: oidc1
      provider_name: authentik
      display_name: Login with</br>Authentik
      base_url: https://authentik.example.com/application/o/wireguard-portal-oauth-application/
      client_id: <client-id>
      client_secret: <client-secret>
      registration_enabled: true
      field_map:
        user_identifier: "preferred_username"
        email: "email"
        firstname: "name"
        is_admin: is_admin
      extra_scopes:
        - profile
        - is_admin
        - email
